#!/bin/bash
echo "doller 1- doller 9 represent positional parameters for arguments one to nine"
echo "for example"
echo "This script name is $0"
echo "The first argument is $2"
echo "The third argument is $3"
echo "The fourth argument is $4"
echo "The fifth argument is $5"
echo "The sixth argument is $6"
echo "The seventh argument is $7"
echo "The eigth argument is $8"
echo "The nineth argument is $9"
echo "$*"
echo "$@"
echo "$#"
echo "$$"
echo "$?"
